services:
  watchii_app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    init: true
    tty: true
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
  node_modules:
